# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-17 03:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperaturaMax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temperaturaMin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humedad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('altitud', models.DecimalField(decimal_places=2, max_digits=5)),
                ('luminosidad', models.DecimalField(decimal_places=2, max_digits=5)),
                ('distanciaLinea', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='FaseCultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('germinacion', models.BooleanField(default=0)),
                ('mergencia', models.BooleanField(default=0)),
                ('hojaPrimaria', models.BooleanField(default=0)),
                ('primeraHoja', models.BooleanField(default=0)),
                ('terceraHoja', models.BooleanField(default=0)),
                ('prefloracion', models.BooleanField(default=0)),
                ('floracion', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Siembra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Simulacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('lineaSiembra', models.IntegerField()),
                ('estado', models.IntegerField()),
                ('configuracion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configurarSimulacion.Configuracion')),
                ('faseCultivo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='configurarSimulacion.FaseCultivo')),
                ('siembra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurarSimulacion.Siembra')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=256)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=9)),
            ],
        ),
        migrations.AddField(
            model_name='simulacion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurarSimulacion.Usuario'),
        ),
    ]
