# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-04 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurarSimulacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='altitud',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='humedad',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
