# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-13 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configurarSimulacion', '0002_auto_20180511_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacion',
            name='siembra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='configurarSimulacion.Siembra'),
        ),
    ]
