# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-13 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurarSimulacion', '0003_auto_20180513_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulacion',
            name='faseCultivo',
            field=models.ManyToManyField(blank=True, to='configurarSimulacion.FaseCultivo'),
        ),
    ]
