# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-14 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurarSimulacion', '0003_auto_20180513_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasecultivo',
            name='floracion',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='fasecultivo',
            name='germinacion',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='fasecultivo',
            name='hojaPrimaria',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='fasecultivo',
            name='mergencia',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='fasecultivo',
            name='prefloracion',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='fasecultivo',
            name='primeraHoja',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='fasecultivo',
            name='terceraHoja',
            field=models.BooleanField(default=0),
        ),
    ]
