# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-05-14 05:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurarSimulacion', '0005_auto_20180513_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fasecultivo',
            name='floracion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fasecultivo',
            name='germinacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fasecultivo',
            name='hojaPrimaria',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fasecultivo',
            name='mergencia',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fasecultivo',
            name='prefloracion',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fasecultivo',
            name='primeraHoja',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fasecultivo',
            name='terceraHoja',
            field=models.IntegerField(null=True),
        ),
    ]
